-- MySQL Script generated by MySQL Workbench
-- Mon May 13 12:08:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema QuizQuestNew
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema QuizQuestNew
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `QuizQuestNew` DEFAULT CHARACTER SET utf8 ;
USE `QuizQuestNew` ;

-- -----------------------------------------------------
-- Table `QuizQuestNew`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuizQuestNew`.`Player` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Origin` VARCHAR(3) NOT NULL,
  `Points` INT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DeletedAt` DATETIME NULL,
  `Role` ENUM("Creator", "Player") NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuizQuestNew`.`Quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuizQuestNew`.`Quiz` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `Category` VARCHAR(45) NOT NULL,
  `Difficulty` ENUM("leicht", "mittel", "schwer") NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Status` ENUM("public", "private") NOT NULL,
  `Joincode` VARCHAR(5) NULL,
  `StartedAt` DATETIME NOT NULL,
  `ClosedAt` DATETIME NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DeletedAt` DATETIME NULL,
  `Creator_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Creator_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Game_Player_idx` (`Creator_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Game_Player`
    FOREIGN KEY (`Creator_ID`)
    REFERENCES `QuizQuestNew`.`Player` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuizQuestNew`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuizQuestNew`.`Question` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(200) NOT NULL,
  `Subcategory` VARCHAR(45) NULL,
  `Image` VARCHAR(45) NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DeletedAt` DATETIME NULL,
  `Quiz_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Quiz_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Question_Game1_idx` (`Quiz_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Question_Game1`
    FOREIGN KEY (`Quiz_ID`)
    REFERENCES `QuizQuestNew`.`Quiz` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuizQuestNew`.`Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuizQuestNew`.`Answer` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(200) NOT NULL,
  `isCorrect` TINYINT NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DeletedAt` DATETIME NULL,
  `Question_ID` INT NOT NULL,
  `Quiz_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Question_ID`, `Quiz_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Answer_Question1_idx` (`Question_ID` ASC, `Quiz_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Answer_Question1`
    FOREIGN KEY (`Question_ID` , `Quiz_ID`)
    REFERENCES `QuizQuestNew`.`Question` (`ID` , `Quiz_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuizQuestNew`.`Badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuizQuestNew`.`Badge` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(200) NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DeletedAt` DATETIME NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuizQuestNew`.`PlayerAnswer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuizQuestNew`.`PlayerAnswer` (
  `Player_ID` INT NOT NULL,
  `Answer_ID` INT NOT NULL,
  `Question_ID` INT NOT NULL,
  `Quiz_ID` INT NOT NULL,
  PRIMARY KEY (`Player_ID`, `Answer_ID`, `Question_ID`, `Quiz_ID`),
  INDEX `fk_Player_has_Answer_Answer1_idx` (`Answer_ID` ASC, `Question_ID` ASC, `Quiz_ID` ASC) VISIBLE,
  INDEX `fk_Player_has_Answer_Player1_idx` (`Player_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Player_has_Answer_Player1`
    FOREIGN KEY (`Player_ID`)
    REFERENCES `QuizQuestNew`.`Player` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Player_has_Answer_Answer1`
    FOREIGN KEY (`Answer_ID` , `Question_ID` , `Quiz_ID`)
    REFERENCES `QuizQuestNew`.`Answer` (`ID` , `Question_ID` , `Quiz_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuizQuestNew`.`PlayerBadge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuizQuestNew`.`PlayerBadge` (
  `Player_ID` INT NOT NULL,
  `Badge_ID` INT NOT NULL,
  PRIMARY KEY (`Player_ID`, `Badge_ID`),
  INDEX `fk_Player_has_Badge_Badge1_idx` (`Badge_ID` ASC) VISIBLE,
  INDEX `fk_Player_has_Badge_Player1_idx` (`Player_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Player_has_Badge_Player1`
    FOREIGN KEY (`Player_ID`)
    REFERENCES `QuizQuestNew`.`Player` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Player_has_Badge_Badge1`
    FOREIGN KEY (`Badge_ID`)
    REFERENCES `QuizQuestNew`.`Badge` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuizQuestNew`.`PlayerQuiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuizQuestNew`.`PlayerQuiz` (
  `Player_ID` INT NOT NULL,
  `Quiz_ID` INT NOT NULL,
  PRIMARY KEY (`Player_ID`, `Quiz_ID`),
  INDEX `fk_Player_has_Quiz_Quiz1_idx` (`Quiz_ID` ASC) VISIBLE,
  INDEX `fk_Player_has_Quiz_Player1_idx` (`Player_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Player_has_Quiz_Player1`
    FOREIGN KEY (`Player_ID`)
    REFERENCES `QuizQuestNew`.`Player` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Player_has_Quiz_Quiz1`
    FOREIGN KEY (`Quiz_ID`)
    REFERENCES `QuizQuestNew`.`Quiz` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
